### ISSUE TITLE
writeJSON is not implemented

### ISSUE THREAD

**Issue by dracupid** [ysmood/nofs#3]
In alias file, there is an alias for `writeJSON` which does not exist in nofs!

**Comment by ysmood** [comment]
Well, apparently, it's a typo. Nofs use `outputJson`. Or is `outputJson` not enough? I think I'd just remove it later.

**Comment by dracupid** [comment]
Hmm.., there is differences between `writeFile` and `ouputFile` as well. Does it mean that writeFile can also be removed?

**Comment by ysmood** [comment]
@dracupid  No, `writeFile` is required, read the doc. To support lower version of node.

> A writeFile shim for < Node v0.10.

For node 0.8, you cannot write something like this `fs.writeFile 'a.txt', { mode: 0o777 }`
