### ISSUE TITLE
glob path starts with ./ doesn't work

### ISSUE THREAD

**Issue by dracupid** [ysmood/nofs#4]
For example: 

``` coffee
nofs.glob './test/a.coffe'
```

shold behave the same as

``` coffee
nofs.glob 'test/a.coffee'
```

Do you think so?

**Comment by ysmood** [comment]
That's a bug of minimatch, I have noticed it since I started this project, and that's why I said I want to write another pattern lib.

You can try yourself:

```
minimatch('abc', './a*') # => false
minimatch('./abc', 'a*') # => false
minimatch('abc', 'a*') # => true
```

You can goto see this issue:  https://github.com/isaacs/minimatch/issues/30
