### ISSUE TITLE
copy method easy to cause EMFILE errors

### ISSUE THREAD

**Issue by kdepp** [ysmood/nofs#8]
easy to cause EMFILE errors when the directory to copy contains more than a hundred files

**Comment by ysmood** [comment]
Have you read the FAQ of nofs? Goto: https://github.com/ysmood/nofs#faq

**Comment by ysmood** [comment]
Please update your Node version or use `graceful-fs` yourself:

``` coffeescript
Object.assign require('fs'), require('graceful-fs')
fs = require 'nofs'
```

**Comment by ysmood** [comment]
By the way you can use `nofs.copySync`, it won't have this issue. I dropped `graceful-fs` after `nofs v0.6.6`.
