### ISSUE TITLE
[EachDir] filter confilcts with minimatch pattern

### ISSUE THREAD

**Issue by dracupid** [ysmood/nofs#9]
When I use a minimatch pattern as spath arg in `eachDir`, filter option will be overwrite.

``` coffee
nofs.eachDir '*',  filter ({isDir}) -> isDir
```

Is this designed or not considered?

see: https://github.com/ysmood/nofs/blob/master/src/main.coffee?source#L452

**Comment by ysmood** [comment]
@dracupid Yes, it's by design. See the option `isAutoPmatch`, you can disable it, and it will not be overrided.

**Comment by ysmood** [comment]
@dracupid When you want to filter the minimatch result, use `iter` like `nofs.eachDir '*',  iter: ({isDir}) -> isDir`, not `filter`, the minimatch is just a sugar to help you to create a filter.

**Comment by ysmood** [comment]
@dracupid I optimized it a bit. See the test case  https://github.com/ysmood/nofs/blob/c25119190b1f800ad7ebab7aa3e69124ce1ebf04/test/basic.coffee#L110

If you feel comfortable with the test case, I may release a new version of nofs.

**Comment by dracupid** [comment]
Good job :+1:

**Comment by ysmood** [comment]
v0.9.5
